import { Shield, Lock, Eye, AlertTriangle, ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';

interface AboutPageProps {
  onNavigate: (page: string) => void;
}

export function AboutPage({ onNavigate }: AboutPageProps) {
  const [openFAQ, setOpenFAQ] = useState<number | null>(0);

  const faqs = [
    {
      question: "How does PixelProof detect deepfakes?",
      answer: "PixelProof uses advanced deep learning models trained on millions of real and synthetic media samples. Our multi-modal approach analyzes facial features, audio-visual synchronization, compression artifacts, noise patterns, and other technical indicators that are characteristic of AI-generated or manipulated content."
    },
    {
      question: "What types of media can PixelProof analyze?",
      answer: "PixelProof currently supports image formats (JPG, PNG, WEBP) and video formats (MP4, MOV) up to 50MB. We analyze both face-swap deepfakes, voice synthesis, and fully synthetic media generated by AI models."
    },
    {
      question: "How accurate is the detection?",
      answer: "Our system achieves 99.8% accuracy on our test datasets, which include the latest deepfake generation techniques. However, as deepfake technology evolves, we continuously retrain our models to maintain high detection rates. Results should be considered alongside other verification methods."
    },
    {
      question: "What happens to my uploaded files?",
      answer: "Your privacy is our top priority. All uploaded files are processed in memory on secure servers and are permanently deleted immediately after analysis. We do not store, log, or share any of your media. Analysis results are only temporarily cached in your browser session."
    },
    {
      question: "Can PixelProof be fooled?",
      answer: "While our models are highly sophisticated, no detection system is perfect. Extremely high-quality deepfakes or novel generation techniques may occasionally evade detection. We recommend using PixelProof as part of a comprehensive verification strategy, especially for high-stakes decisions."
    },
    {
      question: "Is there an API for developers?",
      answer: "Yes! We offer a REST API for developers and enterprises to integrate deepfake detection into their applications. Visit our API Docs page for endpoints, authentication, and code examples. Free tier includes 100 requests per month."
    },
    {
      question: "How fast is the analysis?",
      answer: "Most analyses complete in under 3 seconds for images and under 10 seconds for videos, depending on file size and resolution. Our infrastructure is optimized for low-latency inference using GPU acceleration."
    },
    {
      question: "Can I use PixelProof for commercial purposes?",
      answer: "Yes, we offer commercial licenses and enterprise plans with higher rate limits, batch processing, and dedicated support. Contact our sales team for custom solutions tailored to your organization's needs."
    }
  ];

  return (
    <div className="container mx-auto px-6 py-16 min-h-screen">
      <div className="max-w-4xl mx-auto">
        {/* About Section */}
        <section className="mb-20">
          <h1 className="text-4xl md:text-5xl font-bold mb-6 text-center">
            About{' '}
            <span className="bg-gradient-to-r from-[#00D9FF] to-[#9333EA] bg-clip-text text-transparent">
              PixelProof
            </span>
          </h1>
          
          <div className="mb-12 p-8 rounded-2xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10">
            <p className="text-lg text-gray-300 leading-relaxed mb-6">
              PixelProof is a cutting-edge AI platform dedicated to combating misinformation and ensuring media authenticity in the digital age. Founded in 2023 by a team of AI researchers and cybersecurity experts, our mission is to empower individuals, journalists, and organizations with the tools they need to verify the authenticity of digital media.
            </p>
            <p className="text-lg text-gray-300 leading-relaxed">
              As deepfake technology becomes increasingly sophisticated, the need for reliable detection has never been more critical. PixelProof combines state-of-the-art computer vision, audio analysis, and pattern recognition to identify even the most subtle signs of manipulation, helping restore trust in digital content.
            </p>
          </div>

          {/* Mission & Values */}
          <div className="grid md:grid-cols-2 gap-6 mb-12">
            <div className="p-6 rounded-xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10">
              <div className="w-12 h-12 rounded-lg bg-[#00D9FF]/10 flex items-center justify-center mb-4">
                <Shield className="w-6 h-6 text-[#00D9FF]" />
              </div>
              <h3 className="text-xl font-bold mb-3">Our Mission</h3>
              <p className="text-gray-400">
                To provide accessible, accurate, and privacy-preserving deepfake detection technology that empowers truth and combats misinformation at scale.
              </p>
            </div>
            <div className="p-6 rounded-xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10">
              <div className="w-12 h-12 rounded-lg bg-[#00D9FF]/10 flex items-center justify-center mb-4">
                <Lock className="w-6 h-6 text-[#00D9FF]" />
              </div>
              <h3 className="text-xl font-bold mb-3">Privacy First</h3>
              <p className="text-gray-400">
                We never store your uploaded media. All processing happens in secure, ephemeral environments and data is deleted immediately after analysis.
              </p>
            </div>
          </div>
        </section>

        {/* Ethical Use Section */}
        <section className="mb-20">
          <h2 className="text-3xl font-bold mb-8 text-center">
            Ethical Use & Responsible AI
          </h2>
          
          <div className="p-8 rounded-2xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10 mb-6">
            <div className="flex gap-4 mb-4">
              <Eye className="w-6 h-6 text-[#00D9FF] flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-bold mb-3">Commitment to Responsible Use</h3>
                <p className="text-gray-300 leading-relaxed mb-4">
                  PixelProof is designed to be a force for good in the fight against misinformation. We are committed to:
                </p>
                <ul className="space-y-2 text-gray-300">
                  <li className="flex gap-2">
                    <span className="text-[#00D9FF] mt-1">•</span>
                    <span>Transparency in our detection methods and limitations</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00D9FF] mt-1">•</span>
                    <span>Protecting user privacy and data security</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00D9FF] mt-1">•</span>
                    <span>Preventing misuse for surveillance or harassment</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00D9FF] mt-1">•</span>
                    <span>Continuous improvement and adaptation to new threats</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div className="p-6 rounded-xl bg-orange-500/10 border border-orange-500/30">
            <div className="flex gap-4">
              <AlertTriangle className="w-6 h-6 text-orange-400 flex-shrink-0 mt-0.5" />
              <div>
                <h4 className="font-semibold mb-2 text-orange-300">Important Notice</h4>
                <p className="text-sm text-gray-300">
                  PixelProof is not designed to identify specific individuals or be used for unauthorized surveillance. We prohibit the use of our platform for harassment, defamation, or any illegal activities. Users must comply with all applicable laws and regulations.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Limitations Section */}
        <section className="mb-20">
          <h2 className="text-3xl font-bold mb-8 text-center">Known Limitations</h2>
          
          <div className="p-8 rounded-2xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10">
            <p className="text-gray-300 leading-relaxed mb-6">
              While PixelProof represents the state-of-the-art in deepfake detection, we believe in transparency about our system's limitations:
            </p>
            <ul className="space-y-4 text-gray-300">
              <li className="flex gap-3">
                <span className="text-[#00D9FF] font-bold">1.</span>
                <div>
                  <span className="font-semibold">Evolving Threats:</span> Deepfake generation technology is constantly improving. New techniques may temporarily evade detection until our models are retrained.
                </div>
              </li>
              <li className="flex gap-3">
                <span className="text-[#00D9FF] font-bold">2.</span>
                <div>
                  <span className="font-semibold">Quality Dependence:</span> Low-resolution or heavily compressed media may reduce detection accuracy as artifacts become harder to identify.
                </div>
              </li>
              <li className="flex gap-3">
                <span className="text-[#00D9FF] font-bold">3.</span>
                <div>
                  <span className="font-semibold">Context Matters:</span> Our system analyzes technical indicators, not semantic content. It cannot determine if media is misleading through context manipulation.
                </div>
              </li>
              <li className="flex gap-3">
                <span className="text-[#00D9FF] font-bold">4.</span>
                <div>
                  <span className="font-semibold">Not Legal Proof:</span> While highly accurate, PixelProof results should not be treated as definitive legal evidence without corroboration.
                </div>
              </li>
            </ul>
          </div>
        </section>

        {/* FAQ Section */}
        <section>
          <h2 className="text-3xl font-bold mb-8 text-center">
            Frequently Asked Questions
          </h2>
          
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="rounded-xl bg-gradient-to-br from-[#111827]/80 to-[#1F2937]/80 backdrop-blur-md border border-white/10 overflow-hidden"
              >
                <button
                  onClick={() => setOpenFAQ(openFAQ === index ? null : index)}
                  className="w-full p-6 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
                >
                  <h3 className="text-lg font-semibold pr-4">{faq.question}</h3>
                  {openFAQ === index ? (
                    <ChevronUp className="w-5 h-5 text-[#00D9FF] flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-400 flex-shrink-0" />
                  )}
                </button>
                {openFAQ === index && (
                  <div className="px-6 pb-6">
                    <p className="text-gray-300 leading-relaxed">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <div className="mt-16 text-center p-8 rounded-2xl bg-gradient-to-r from-[#00D9FF]/10 to-[#9333EA]/10 border border-[#00D9FF]/30">
          <h3 className="text-2xl font-bold mb-4">Ready to get started?</h3>
          <p className="text-gray-300 mb-6">
            Start analyzing media for deepfakes with our advanced AI detection system.
          </p>
          <button 
            onClick={() => onNavigate('analyze')}
            className="bg-[#00D9FF] hover:bg-[#00C4E6] text-black px-8 py-3 rounded-lg font-semibold transition-all hover:shadow-lg hover:shadow-cyan-500/50"
          >
            Try PixelProof Now
          </button>
        </div>
      </div>
    </div>
  );
}
